mod history;
use std::time::{SystemTime, UNIX_EPOCH};

use base64::{Engine, engine::general_purpose::STANDARD};
use llmproxy_core::protocol::{MessagesAuth, Protocol};
use llmproxy_store::{
    ModelMappingInput, ModelRouteInput, ModelRouteTargetInput, ProviderInput, ProviderPaths,
    ProviderStore, StoreError,
};

fn input(name: &str, protocol: Protocol) -> ProviderInput {
    ProviderInput {
        name: name.into(),
        paths: ProviderPaths::single(protocol),
        host: "api.example.com".into(),
        port: 443,
        tls: true,
        api_key: "test-key-do-not-return".into(),
        enabled: true,
        models_path: "/models".into(),
        models_protocol: protocol,
        anthropic_version: (protocol == Protocol::AnthropicMessages).then(|| "2023-06-01".into()),
        messages_auth: MessagesAuth::ApiKey,
        connect_timeout_ms: 10_000,
        read_timeout_ms: 60_000,
        write_timeout_ms: 30_000,
    }
}

/// Every run owns a fresh schema. It never resets a database or touches existing
/// application tables, and always drops only the schema generated by this run.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn postgresql_provider_lifecycle_and_concurrency() {
    let Ok(base_url) = std::env::var("LLMPROXY_TEST_DATABASE_URL") else {
        eprintln!("跳过 PostgreSQL 集成测试：未设置 LLMPROXY_TEST_DATABASE_URL");
        return;
    };
    let mut admin = toasty::Db::builder()
        .connect(&base_url)
        .await
        .unwrap_or_else(|_| panic!("无法连接 LLMPROXY_TEST_DATABASE_URL"));
    let schema = format!(
        "llmproxy_test_{}_{}",
        std::process::id(),
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    );
    toasty::sql::statement(format!("CREATE SCHEMA {schema}"))
        .exec(&mut admin)
        .await
        .unwrap_or_else(|_| panic!("无法创建独立测试 schema"));
    let separator = if base_url.contains('?') { '&' } else { '?' };
    let url = format!("{base_url}{separator}options=-c%20search_path%3D{schema}");
    let worker = tokio::spawn(async move {
        exercise_store(&url, false).await;
    });
    let result = worker.await;
    toasty::sql::statement(format!("DROP SCHEMA {schema} CASCADE"))
        .exec(&mut admin)
        .await
        .unwrap_or_else(|_| panic!("无法清理独立测试 schema：{schema}"));
    result.unwrap();
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn sqlite_provider_lifecycle_and_concurrency() {
    let directory = std::env::temp_dir().join(format!(
        "llmproxy-store-sqlite-{}-{}",
        std::process::id(),
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    std::fs::create_dir(&directory).unwrap();
    let url = format!("sqlite:{}", directory.join("providers.sqlite3").display());
    exercise_store(&url, true).await;
    std::fs::remove_dir_all(directory).unwrap();
}

async fn exercise_store(url: &str, sqlite: bool) {
    let key = STANDARD.encode([7; 32]);
    let store = ProviderStore::connect(url, &key).await.unwrap();
    assert!(
        store.list().await.is_err(),
        "connect must not migrate implicitly"
    );
    if sqlite {
        store.migrate().await.unwrap();
        store.migrate().await.unwrap();
    } else {
        // PostgreSQL serializes concurrent startups with an advisory lock.
        let (first, second) = tokio::join!(store.migrate(), store.migrate());
        first.unwrap();
        second.unwrap();
    }
    assert!(store.list().await.unwrap().is_empty());
    assert!(store.load_active().await.unwrap().is_empty());
    exercise_tool_continuations(&store, url, &key).await;
    history::exercise(&store, url, &key).await;

    // An empty migrated database is already bound to its first master key.
    let wrong_key = ProviderStore::connect(url, &STANDARD.encode([8; 32]))
        .await
        .unwrap();
    assert!(matches!(
        wrong_key.migrate().await,
        Err(StoreError::Configuration(_))
    ));
    assert!(matches!(
        wrong_key.list().await,
        Err(StoreError::Configuration(_))
    ));
    assert!(matches!(
        wrong_key.load_active().await,
        Err(StoreError::Configuration(_))
    ));
    assert!(matches!(
        wrong_key
            .create(input("Wrong key", Protocol::OpenAiChat))
            .await,
        Err(StoreError::Configuration(_))
    ));
    assert!(store.list().await.unwrap().is_empty());

    let chat = store
        .create(input("Chat Primary", Protocol::OpenAiChat))
        .await
        .unwrap();
    let responses = store
        .create(input("Responses", Protocol::OpenAiResponses))
        .await
        .unwrap();
    let messages = store
        .create(input("Messages", Protocol::AnthropicMessages))
        .await
        .unwrap();
    assert!(chat.key_configured);
    assert!(!chat.active);
    assert!(chat.enabled);
    let rejected_delete = store.delete(chat.id, chat.version).await.unwrap_err();
    assert!(matches!(rejected_delete, StoreError::Conflict(_)));
    assert!(rejected_delete.to_string().contains("先停用"));
    let unchanged = store.get(chat.id).await.unwrap();
    assert!(unchanged.enabled && !unchanged.active);
    assert_eq!(unchanged.version, chat.version);
    assert!(!format!("{chat:?}").contains("test-key-do-not-return"));
    assert!(matches!(
        store
            .create(input("Chat Primary", Protocol::OpenAiChat))
            .await,
        Err(StoreError::Conflict(_))
    ));

    for view in [&chat, &responses, &messages] {
        store
            .activate(view.id, view.version, view.paths.supported()[0])
            .await
            .unwrap();
    }
    let active = store.load_active().await.unwrap();
    assert_eq!(active.len(), 3);
    assert!(
        active
            .iter()
            .all(|provider| provider.secret == "test-key-do-not-return")
    );

    // Migrations and process restarts preserve records and configuration.
    store.migrate().await.unwrap();
    let reopened = ProviderStore::connect(url, &key).await.unwrap();
    assert_eq!(reopened.list().await.unwrap().len(), 3);
    assert_eq!(reopened.load_active().await.unwrap().len(), 3);
    assert!(matches!(
        wrong_key.load_active().await,
        Err(StoreError::Configuration(_))
    ));

    let current = store.get(chat.id).await.unwrap();
    assert!(current.active);
    assert!(current.version > chat.version);
    assert!(matches!(
        wrong_key.migrate().await,
        Err(StoreError::Configuration(_))
    ));
    assert!(matches!(
        wrong_key.list().await,
        Err(StoreError::Configuration(_))
    ));
    assert!(matches!(
        wrong_key.get(chat.id).await,
        Err(StoreError::Configuration(_))
    ));
    assert!(matches!(
        wrong_key
            .create(input("Wrong key", Protocol::OpenAiChat))
            .await,
        Err(StoreError::Configuration(_))
    ));
    let mut wrong_rotation = input("Wrong rotation", Protocol::OpenAiChat);
    wrong_rotation.api_key = "different-provider-key".into();
    assert!(matches!(
        wrong_key
            .update(chat.id, current.version, wrong_rotation)
            .await,
        Err(StoreError::Configuration(_))
    ));
    assert!(matches!(
        wrong_key
            .activate(chat.id, current.version, Protocol::OpenAiChat)
            .await,
        Err(StoreError::Configuration(_))
    ));
    assert!(matches!(
        wrong_key.set_enabled(chat.id, current.version, false).await,
        Err(StoreError::Configuration(_))
    ));
    assert!(matches!(
        wrong_key.delete(chat.id, current.version).await,
        Err(StoreError::Configuration(_))
    ));
    let unchanged = store.get(chat.id).await.unwrap();
    assert_eq!(unchanged.name, current.name);
    assert_eq!(unchanged.version, current.version);
    assert_eq!(unchanged.updated_at, current.updated_at);
    assert!(unchanged.enabled && unchanged.active);
    assert_eq!(store.list().await.unwrap().len(), 3);
    assert!(
        store
            .load_active()
            .await
            .unwrap()
            .iter()
            .all(|p| p.secret == "test-key-do-not-return")
    );

    // Simulate upgrading records created before the database verifier existed.
    // Wrong keys must not be able to claim that legacy database.
    let mut inspect = toasty::Db::builder().connect(url).await.unwrap();
    toasty::sql::statement("DELETE FROM store_keys")
        .exec(&mut inspect)
        .await
        .unwrap();
    assert!(matches!(
        store.list().await,
        Err(StoreError::Configuration(_))
    ));
    assert!(matches!(
        wrong_key.migrate().await,
        Err(StoreError::Configuration(_))
    ));
    assert!(
        toasty::sql::query("SELECT id FROM store_keys")
            .exec(&mut inspect)
            .await
            .unwrap()
            .is_empty()
    );
    store.migrate().await.unwrap();
    assert_eq!(store.get(chat.id).await.unwrap().version, current.version);
    assert!(
        store
            .load_active()
            .await
            .unwrap()
            .iter()
            .all(|p| p.secret == "test-key-do-not-return")
    );
    assert!(matches!(
        wrong_key.list().await,
        Err(StoreError::Configuration(_))
    ));
    assert!(matches!(
        store
            .update(chat.id, chat.version, input("Stale", Protocol::OpenAiChat))
            .await,
        Err(StoreError::Conflict(_))
    ));
    assert!(matches!(
        store.delete(chat.id, current.version).await,
        Err(StoreError::Conflict(_))
    ));
    let mut edit = input("Chat Renamed", Protocol::OpenAiChat);
    edit.api_key.clear();
    edit.host = "renamed.example.com".into();
    let edited = store.update(chat.id, current.version, edit).await.unwrap();
    assert_eq!(edited.name, "Chat Renamed");
    assert_eq!(
        store
            .load_active()
            .await
            .unwrap()
            .into_iter()
            .find(|p| p.id == chat.id)
            .unwrap()
            .secret,
        "test-key-do-not-return"
    );

    let mut replacement = input("Chat Renamed", Protocol::OpenAiChat);
    replacement.api_key = "rotated-provider-key".into();
    let rotated = store
        .update(chat.id, edited.version, replacement)
        .await
        .unwrap();
    assert_eq!(
        store
            .load_active()
            .await
            .unwrap()
            .into_iter()
            .find(|p| p.id == chat.id)
            .unwrap()
            .secret,
        "rotated-provider-key"
    );

    // Simultaneous actions use the same optimistic version: exactly one wins.
    let (disabled, activated) = tokio::join!(
        store.set_enabled(chat.id, rotated.version, false),
        reopened.activate(chat.id, rotated.version, Protocol::OpenAiChat),
    );
    assert_ne!(disabled.is_ok(), activated.is_ok());
    let loser = if disabled.is_err() {
        disabled
    } else {
        activated
    };
    assert!(matches!(loser, Err(StoreError::Conflict(_))));
    let current = store.get(chat.id).await.unwrap();
    if current.enabled {
        store
            .set_enabled(chat.id, current.version, false)
            .await
            .unwrap();
    }
    let disabled = store.get(chat.id).await.unwrap();
    assert!(!disabled.enabled);
    assert!(!disabled.active);
    assert!(
        !store
            .load_active()
            .await
            .unwrap()
            .iter()
            .any(|p| p.id == chat.id)
    );
    assert!(matches!(
        store
            .activate(chat.id, disabled.version, Protocol::OpenAiChat)
            .await,
        Err(StoreError::Conflict(_))
    ));
    store.delete(chat.id, disabled.version).await.unwrap();
    assert!(matches!(
        store.get(chat.id).await,
        Err(StoreError::NotFound)
    ));

    // Switching a route invalidates stale forms for the old active provider.
    let backup = store
        .create(input("Responses Backup", Protocol::OpenAiResponses))
        .await
        .unwrap();
    let old = store.get(responses.id).await.unwrap();
    store
        .activate(backup.id, backup.version, Protocol::OpenAiResponses)
        .await
        .unwrap();
    assert!(!store.get(responses.id).await.unwrap().active);
    assert!(matches!(
        store.set_enabled(responses.id, old.version, false).await,
        Err(StoreError::Conflict(_))
    ));
    let backup = store.get(backup.id).await.unwrap();
    let mut edit = input("Responses Backup", Protocol::OpenAiResponses);
    edit.api_key.clear();
    edit.enabled = false;
    let disabled = store.update(backup.id, backup.version, edit).await.unwrap();
    assert!(!disabled.active);

    // Database contains only authenticated ciphertext, never the entered key.
    let rows = toasty::sql::query("SELECT encrypted_key FROM providers")
        .exec(&mut inspect)
        .await
        .unwrap();
    let stored = format!("{rows:?}");
    assert!(stored.contains("v1:"));
    assert!(!stored.contains("test-key-do-not-return"));
    assert!(!stored.contains("rotated-provider-key"));

    let mut mixed = input("Mixed interfaces", Protocol::OpenAiChat);
    mixed.paths.openai_chat = Some("/custom/chat".into());
    mixed.paths.openai_responses = Some("/custom/responses".into());
    mixed.models_path = "/v1/models".into();
    let mixed = store.create(mixed).await.unwrap();
    assert_eq!(mixed.paths.supported().len(), 2);
    assert_eq!(mixed.models_path, "/v1/models");
    store
        .activate(mixed.id, mixed.version, Protocol::OpenAiChat)
        .await
        .unwrap();
    let mixed = store.get(mixed.id).await.unwrap();
    store
        .activate(mixed.id, mixed.version, Protocol::OpenAiResponses)
        .await
        .unwrap();
    let mixed = store.get(mixed.id).await.unwrap();
    assert_eq!(mixed.active_protocols.len(), 2);
    let routes = store.load_active().await.unwrap();
    assert_eq!(
        routes
            .iter()
            .find(|route| route.protocol == Protocol::OpenAiChat)
            .unwrap()
            .upstream_path,
        "/custom/chat"
    );
    assert_eq!(
        routes
            .iter()
            .find(|route| route.protocol == Protocol::OpenAiResponses)
            .unwrap()
            .upstream_path,
        "/custom/responses"
    );
    let probe = store.probe_target(mixed.id).await.unwrap();
    assert_eq!(probe.path, "/v1/models");
    assert_eq!(probe.secret, "test-key-do-not-return");
    let mut remove_active = input("Mixed interfaces", Protocol::OpenAiResponses);
    remove_active.api_key.clear();
    let removed = store
        .update(mixed.id, mixed.version, remove_active)
        .await
        .unwrap();
    assert!(removed.paths.openai_chat.is_none());
    assert_eq!(removed.active_protocols, vec![Protocol::OpenAiResponses]);
    let mut invalid_path = input("Invalid path", Protocol::OpenAiChat);
    invalid_path.paths.openai_chat = Some("https://other.example/v1/chat".into());
    assert!(matches!(
        store.create(invalid_path).await,
        Err(StoreError::Validation(_))
    ));

    let thinking = llmproxy_core::thinking::Config {
        support: llmproxy_core::thinking::Support::Switchable,
        enabled: llmproxy_core::ir::request::controls::Reasoning {
            effort: Some("medium".into()),
            ..Default::default()
        },
    };
    let mapping_input = ModelMappingInput {
        thinking: thinking.clone(),
        alias: "mixed/model-a".into(),
        provider_id: mixed.id,
        upstream_model_id: "model-a".into(),
        protocols: vec![Protocol::OpenAiResponses],
        reference_price: None,
    };
    let mapping = store.create_model(mapping_input.clone()).await.unwrap();
    let route = store
        .create_route(ModelRouteInput {
            name: "mixed/public".into(),
            protocol: Protocol::OpenAiResponses,
            provider_protocol: Protocol::OpenAiResponses,
            enabled: true,
            targets: vec![ModelRouteTargetInput {
                model_id: mapping.id,
                enabled: true,
            }],
        })
        .await
        .unwrap();
    let loaded = store.load_model_routes().await.unwrap();
    assert_eq!(loaded.len(), 2);
    assert!(loaded.iter().all(|r| r.thinking == thinking));
    assert_eq!(
        store.get_model(mapping.id).await.unwrap().thinking,
        thinking
    );
    store.migrate().await.unwrap();
    let reopened = ProviderStore::connect(url, &key).await.unwrap();
    assert_eq!(
        reopened.get_model(mapping.id).await.unwrap().thinking,
        thinking
    );
    let mut remove_mapped_protocol = input("Mixed interfaces", Protocol::OpenAiChat);
    remove_mapped_protocol.api_key.clear();
    assert!(matches!(
        store
            .update(mixed.id, removed.version, remove_mapped_protocol)
            .await,
        Err(StoreError::Conflict(_))
    ));
    assert!(matches!(
        store.create_model(mapping_input.clone()).await,
        Err(StoreError::Conflict(_))
    ));
    let updated = store
        .update_model(
            mapping.id,
            mapping.version,
            ModelMappingInput {
                thinking: Default::default(),
                alias: "mixed/model-b".into(),
                ..mapping_input
            },
        )
        .await
        .unwrap();
    assert_eq!(updated.alias, "mixed/model-b");
    assert_eq!(updated.thinking, Default::default());
    assert!(
        store
            .load_model_routes()
            .await
            .unwrap()
            .iter()
            .all(|r| r.thinking == Default::default())
    );
    assert!(matches!(
        store.delete_model(mapping.id, mapping.version).await,
        Err(StoreError::Conflict(_))
    ));
    assert!(matches!(
        store.delete_model(mapping.id, updated.version).await,
        Err(StoreError::Conflict(_))
    ));
    store.delete_route(route.id, route.version).await.unwrap();
    store
        .delete_model(mapping.id, updated.version)
        .await
        .unwrap();
    assert!(store.load_model_routes().await.unwrap().is_empty());

    let messages = store
        .create(input("Bearer Messages", Protocol::AnthropicMessages))
        .await
        .unwrap();
    assert_eq!(messages.messages_auth, MessagesAuth::ApiKey);
    let mut edited = input("Bearer Messages", Protocol::AnthropicMessages);
    edited.api_key.clear();
    edited.messages_auth = MessagesAuth::Bearer;
    store
        .update(messages.id, messages.version, edited)
        .await
        .unwrap();
    let reopened = ProviderStore::connect(url, &key).await.unwrap();
    assert_eq!(
        reopened.get(messages.id).await.unwrap().messages_auth,
        MessagesAuth::Bearer
    );
}

/// SQLite 和独立 PG schema 共用验收：跨连接、作用域、并发保存和错误主密钥。
async fn exercise_tool_continuations(store: &ProviderStore, url: &str, key: &str) {
    use llmproxy_store::ToolContinuation;
    let scope = "a".repeat(64);
    let make = |id: &str| ToolContinuation {
        id: id.into(),
        scope: scope.clone(),
        payload: "private-signature-and-args".into(),
    };
    let first = [make("call_test_a")];
    let second = [make("call_test_b")];
    let (a, b) = tokio::join!(
        store.save_tool_continuations(&first),
        store.save_tool_continuations(&second)
    );
    a.unwrap();
    b.unwrap();
    let ids = vec!["call_test_a".into(), "call_test_b".into()];
    let peer = ProviderStore::connect(url, key).await.unwrap();
    let loaded = peer.load_tool_continuations(&ids, &scope).await.unwrap();
    assert!(
        loaded
            .iter()
            .all(|record| record.payload == "private-signature-and-args")
    );
    assert!(matches!(
        peer.load_tool_continuations(&ids, &"b".repeat(64)).await,
        Err(StoreError::NotFound)
    ));
    peer.touch_tool_continuations(&ids, &scope).await.unwrap();
    let wrong_key = ProviderStore::connect(url, &STANDARD.encode([8; 32]))
        .await
        .unwrap();
    assert!(matches!(
        wrong_key.load_tool_continuations(&ids, &scope).await,
        Err(StoreError::Configuration(_))
    ));
    assert!(matches!(
        wrong_key.touch_tool_continuations(&ids, &scope).await,
        Err(StoreError::Configuration(_))
    ));
    assert!(matches!(
        wrong_key
            .save_tool_continuations(&[make("call_wrong_key")])
            .await,
        Err(StoreError::Configuration(_))
    ));
}
