use std::time::{SystemTime, UNIX_EPOCH};

use base64::{Engine, engine::general_purpose::STANDARD};
use llmproxy_core::protocol::Protocol;
use llmproxy_store::{ProviderInput, ProviderStore, StoreError};

fn input(name: &str, protocol: Protocol) -> ProviderInput {
    ProviderInput {
        name: name.into(),
        protocol,
        host: "api.example.com".into(),
        port: 443,
        tls: true,
        api_key: "test-key-do-not-return".into(),
        enabled: true,
        anthropic_version: (protocol == Protocol::AnthropicMessages).then(|| "2023-06-01".into()),
        connect_timeout_ms: 10_000,
        read_timeout_ms: 60_000,
        write_timeout_ms: 30_000,
    }
}

/// Every run owns a fresh schema. It never resets a database or touches existing
/// application tables, and always drops only the schema generated by this run.
#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn postgresql_provider_lifecycle_and_concurrency() {
    let Ok(base_url) = std::env::var("LLMPROXY_TEST_DATABASE_URL") else {
        eprintln!("跳过 PostgreSQL 集成测试：未设置 LLMPROXY_TEST_DATABASE_URL");
        return;
    };
    let mut admin = toasty::Db::builder()
        .connect(&base_url)
        .await
        .unwrap_or_else(|_| panic!("无法连接 LLMPROXY_TEST_DATABASE_URL"));
    let schema = format!(
        "llmproxy_test_{}_{}",
        std::process::id(),
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    );
    toasty::sql::statement(format!("CREATE SCHEMA {schema}"))
        .exec(&mut admin)
        .await
        .unwrap_or_else(|_| panic!("无法创建独立测试 schema"));
    let separator = if base_url.contains('?') { '&' } else { '?' };
    let url = format!("{base_url}{separator}options=-c%20search_path%3D{schema}");
    let worker = tokio::spawn(async move {
        exercise_store(&url, false).await;
    });
    let result = worker.await;
    toasty::sql::statement(format!("DROP SCHEMA {schema} CASCADE"))
        .exec(&mut admin)
        .await
        .unwrap_or_else(|_| panic!("无法清理独立测试 schema：{schema}"));
    result.unwrap();
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn sqlite_provider_lifecycle_and_concurrency() {
    let directory = std::env::temp_dir().join(format!(
        "llmproxy-store-sqlite-{}-{}",
        std::process::id(),
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    std::fs::create_dir(&directory).unwrap();
    let url = format!("sqlite:{}", directory.join("providers.sqlite3").display());
    exercise_store(&url, true).await;
    std::fs::remove_dir_all(directory).unwrap();
}

async fn exercise_store(url: &str, sqlite: bool) {
    let key = STANDARD.encode([7; 32]);
    let store = ProviderStore::connect(url, &key).await.unwrap();
    assert!(
        store.list().await.is_err(),
        "connect must not migrate implicitly"
    );
    if sqlite {
        store.migrate().await.unwrap();
        store.migrate().await.unwrap();
    } else {
        // PostgreSQL serializes concurrent startups with an advisory lock.
        let (first, second) = tokio::join!(store.migrate(), store.migrate());
        first.unwrap();
        second.unwrap();
    }
    assert!(store.list().await.unwrap().is_empty());
    assert!(store.load_active().await.unwrap().is_empty());

    // An empty migrated database is already bound to its first master key.
    let wrong_key = ProviderStore::connect(url, &STANDARD.encode([8; 32]))
        .await
        .unwrap();
    assert!(matches!(
        wrong_key.migrate().await,
        Err(StoreError::Configuration(_))
    ));
    assert!(matches!(
        wrong_key.list().await,
        Err(StoreError::Configuration(_))
    ));
    assert!(matches!(
        wrong_key.load_active().await,
        Err(StoreError::Configuration(_))
    ));
    assert!(matches!(
        wrong_key
            .create(input("Wrong key", Protocol::OpenAiChat))
            .await,
        Err(StoreError::Configuration(_))
    ));
    assert!(store.list().await.unwrap().is_empty());

    let chat = store
        .create(input("Chat Primary", Protocol::OpenAiChat))
        .await
        .unwrap();
    let responses = store
        .create(input("Responses", Protocol::OpenAiResponses))
        .await
        .unwrap();
    let messages = store
        .create(input("Messages", Protocol::AnthropicMessages))
        .await
        .unwrap();
    assert!(chat.key_configured);
    assert!(!chat.active);
    assert!(chat.enabled);
    let rejected_delete = store.delete(chat.id, chat.version).await.unwrap_err();
    assert!(matches!(rejected_delete, StoreError::Conflict(_)));
    assert!(rejected_delete.to_string().contains("先停用"));
    let unchanged = store.get(chat.id).await.unwrap();
    assert!(unchanged.enabled && !unchanged.active);
    assert_eq!(unchanged.version, chat.version);
    assert!(!format!("{chat:?}").contains("test-key-do-not-return"));
    assert!(matches!(
        store
            .create(input("Chat Primary", Protocol::OpenAiChat))
            .await,
        Err(StoreError::Conflict(_))
    ));

    for view in [&chat, &responses, &messages] {
        store.activate(view.id, view.version).await.unwrap();
    }
    let active = store.load_active().await.unwrap();
    assert_eq!(active.len(), 3);
    assert!(
        active
            .iter()
            .all(|provider| provider.secret == "test-key-do-not-return")
    );

    // Migrations and process restarts preserve records and configuration.
    store.migrate().await.unwrap();
    let reopened = ProviderStore::connect(url, &key).await.unwrap();
    assert_eq!(reopened.list().await.unwrap().len(), 3);
    assert_eq!(reopened.load_active().await.unwrap().len(), 3);
    assert!(matches!(
        wrong_key.load_active().await,
        Err(StoreError::Configuration(_))
    ));

    let current = store.get(chat.id).await.unwrap();
    assert!(current.active);
    assert!(current.version > chat.version);
    assert!(matches!(
        wrong_key.migrate().await,
        Err(StoreError::Configuration(_))
    ));
    assert!(matches!(
        wrong_key.list().await,
        Err(StoreError::Configuration(_))
    ));
    assert!(matches!(
        wrong_key.get(chat.id).await,
        Err(StoreError::Configuration(_))
    ));
    assert!(matches!(
        wrong_key
            .create(input("Wrong key", Protocol::OpenAiChat))
            .await,
        Err(StoreError::Configuration(_))
    ));
    let mut wrong_rotation = input("Wrong rotation", Protocol::OpenAiChat);
    wrong_rotation.api_key = "different-provider-key".into();
    assert!(matches!(
        wrong_key
            .update(chat.id, current.version, wrong_rotation)
            .await,
        Err(StoreError::Configuration(_))
    ));
    assert!(matches!(
        wrong_key.activate(chat.id, current.version).await,
        Err(StoreError::Configuration(_))
    ));
    assert!(matches!(
        wrong_key.set_enabled(chat.id, current.version, false).await,
        Err(StoreError::Configuration(_))
    ));
    assert!(matches!(
        wrong_key.delete(chat.id, current.version).await,
        Err(StoreError::Configuration(_))
    ));
    let unchanged = store.get(chat.id).await.unwrap();
    assert_eq!(unchanged.name, current.name);
    assert_eq!(unchanged.version, current.version);
    assert_eq!(unchanged.updated_at, current.updated_at);
    assert!(unchanged.enabled && unchanged.active);
    assert_eq!(store.list().await.unwrap().len(), 3);
    assert!(
        store
            .load_active()
            .await
            .unwrap()
            .iter()
            .all(|p| p.secret == "test-key-do-not-return")
    );

    // Simulate upgrading records created before the database verifier existed.
    // Wrong keys must not be able to claim that legacy database.
    let mut inspect = toasty::Db::builder().connect(url).await.unwrap();
    toasty::sql::statement("DELETE FROM store_keys")
        .exec(&mut inspect)
        .await
        .unwrap();
    assert!(matches!(
        store.list().await,
        Err(StoreError::Configuration(_))
    ));
    assert!(matches!(
        wrong_key.migrate().await,
        Err(StoreError::Configuration(_))
    ));
    assert!(
        toasty::sql::query("SELECT id FROM store_keys")
            .exec(&mut inspect)
            .await
            .unwrap()
            .is_empty()
    );
    store.migrate().await.unwrap();
    assert_eq!(store.get(chat.id).await.unwrap().version, current.version);
    assert!(
        store
            .load_active()
            .await
            .unwrap()
            .iter()
            .all(|p| p.secret == "test-key-do-not-return")
    );
    assert!(matches!(
        wrong_key.list().await,
        Err(StoreError::Configuration(_))
    ));
    assert!(matches!(
        store
            .update(chat.id, chat.version, input("Stale", Protocol::OpenAiChat))
            .await,
        Err(StoreError::Conflict(_))
    ));
    assert!(matches!(
        store.delete(chat.id, current.version).await,
        Err(StoreError::Conflict(_))
    ));
    assert!(matches!(
        store
            .update(
                chat.id,
                current.version,
                input("Changed protocol", Protocol::OpenAiResponses)
            )
            .await,
        Err(StoreError::Conflict(_))
    ));

    let mut edit = input("Chat Renamed", Protocol::OpenAiChat);
    edit.api_key.clear();
    edit.host = "renamed.example.com".into();
    let edited = store.update(chat.id, current.version, edit).await.unwrap();
    assert_eq!(edited.name, "Chat Renamed");
    assert_eq!(
        store
            .load_active()
            .await
            .unwrap()
            .into_iter()
            .find(|p| p.id == chat.id)
            .unwrap()
            .secret,
        "test-key-do-not-return"
    );

    let mut replacement = input("Chat Renamed", Protocol::OpenAiChat);
    replacement.api_key = "rotated-provider-key".into();
    let rotated = store
        .update(chat.id, edited.version, replacement)
        .await
        .unwrap();
    assert_eq!(
        store
            .load_active()
            .await
            .unwrap()
            .into_iter()
            .find(|p| p.id == chat.id)
            .unwrap()
            .secret,
        "rotated-provider-key"
    );

    // Simultaneous actions use the same optimistic version: exactly one wins.
    let (disabled, activated) = tokio::join!(
        store.set_enabled(chat.id, rotated.version, false),
        reopened.activate(chat.id, rotated.version),
    );
    assert_ne!(disabled.is_ok(), activated.is_ok());
    let loser = if disabled.is_err() {
        disabled
    } else {
        activated
    };
    assert!(matches!(loser, Err(StoreError::Conflict(_))));
    let current = store.get(chat.id).await.unwrap();
    if current.enabled {
        store
            .set_enabled(chat.id, current.version, false)
            .await
            .unwrap();
    }
    let disabled = store.get(chat.id).await.unwrap();
    assert!(!disabled.enabled);
    assert!(!disabled.active);
    assert!(
        !store
            .load_active()
            .await
            .unwrap()
            .iter()
            .any(|p| p.id == chat.id)
    );
    assert!(matches!(
        store.activate(chat.id, disabled.version).await,
        Err(StoreError::Conflict(_))
    ));
    store.delete(chat.id, disabled.version).await.unwrap();
    assert!(matches!(
        store.get(chat.id).await,
        Err(StoreError::NotFound)
    ));

    // Switching a route invalidates stale forms for the old active provider.
    let backup = store
        .create(input("Responses Backup", Protocol::OpenAiResponses))
        .await
        .unwrap();
    let old = store.get(responses.id).await.unwrap();
    store.activate(backup.id, backup.version).await.unwrap();
    assert!(!store.get(responses.id).await.unwrap().active);
    assert!(matches!(
        store.set_enabled(responses.id, old.version, false).await,
        Err(StoreError::Conflict(_))
    ));
    let backup = store.get(backup.id).await.unwrap();
    let mut edit = input("Responses Backup", Protocol::OpenAiResponses);
    edit.api_key.clear();
    edit.enabled = false;
    let disabled = store.update(backup.id, backup.version, edit).await.unwrap();
    assert!(!disabled.active);

    // Database contains only authenticated ciphertext, never the entered key.
    let rows = toasty::sql::query("SELECT encrypted_key FROM providers")
        .exec(&mut inspect)
        .await
        .unwrap();
    let stored = format!("{rows:?}");
    assert!(stored.contains("v1:"));
    assert!(!stored.contains("test-key-do-not-return"));
    assert!(!stored.contains("rotated-provider-key"));
}
