[package]
name = "llmproxy-gateway"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
llmproxy-core = { path = "../llmproxy-core" }
llmproxy-store = { path = "../llmproxy-store" }
tokio = { version = "1.53.1", features = ["rt", "macros", "sync", "time", "net"] }
pingora = { version = "0.9.0", features = ["proxy", "rustls"] }
pingora-http = "0.9.0"
async-trait = "0.1.92"
serde.workspace = true
toml = "1.1.6"
tracing.workspace = true
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
tracing-opentelemetry = "0.34.0"
opentelemetry = { version = "0.33.0", features = ["metrics", "trace"] }
opentelemetry_sdk = { version = "0.33.0", features = ["metrics", "trace", "logs"] }
opentelemetry-otlp = { version = "0.33.0", default-features = false, features = ["http-proto", "reqwest-blocking-client", "reqwest-rustls", "trace", "metrics", "logs"] }
opentelemetry-appender-tracing = "0.33.0"

[dev-dependencies]
base64 = "0.23.1"
toasty = { version = "0.10.0", default-features = false, features = ["postgresql"] }
