CREATE TABLE providers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE CHECK (char_length(name) BETWEEN 1 AND 80),
    protocol TEXT NOT NULL CHECK (protocol IN ('openai_chat', 'openai_responses', 'anthropic_messages')),
    host TEXT NOT NULL,
    port INTEGER NOT NULL CHECK (port BETWEEN 1 AND 65535),
    tls BOOLEAN NOT NULL,
    encrypted_key TEXT NOT NULL,
    enabled BOOLEAN NOT NULL,
    anthropic_version TEXT,
    connect_timeout_ms BIGINT NOT NULL CHECK (connect_timeout_ms > 0),
    read_timeout_ms BIGINT NOT NULL CHECK (read_timeout_ms > 0),
    write_timeout_ms BIGINT NOT NULL CHECK (write_timeout_ms > 0),
    version BIGINT NOT NULL DEFAULT 1 CHECK (version > 0),
    updated_at BIGINT NOT NULL
);

CREATE TABLE route_bindings (
    protocol TEXT PRIMARY KEY CHECK (protocol IN ('openai_chat', 'openai_responses', 'anthropic_messages')),
    provider_id BIGINT REFERENCES providers(id) ON DELETE RESTRICT,
    version BIGINT NOT NULL DEFAULT 1 CHECK (version > 0)
);

INSERT INTO route_bindings (protocol) VALUES
    ('openai_chat'), ('openai_responses'), ('anthropic_messages');
