CREATE TABLE model_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alias TEXT NOT NULL UNIQUE CHECK (char_length(alias) BETWEEN 1 AND 200),
    provider_id BIGINT NOT NULL REFERENCES providers(id) ON DELETE RESTRICT,
    upstream_model_id TEXT NOT NULL CHECK (char_length(upstream_model_id) BETWEEN 1 AND 200),
    openai_chat BOOLEAN NOT NULL,
    openai_responses BOOLEAN NOT NULL,
    anthropic_messages BOOLEAN NOT NULL,
    version BIGINT NOT NULL DEFAULT 1 CHECK (version > 0),
    updated_at BIGINT NOT NULL,
    CHECK (openai_chat OR openai_responses OR anthropic_messages)
);

CREATE INDEX model_mappings_provider_id_idx ON model_mappings(provider_id);
