CREATE TABLE model_price_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL REFERENCES providers(id) ON DELETE CASCADE,
    upstream_model_id TEXT NOT NULL CHECK (char_length(upstream_model_id) BETWEEN 1 AND 200),
    currency TEXT NOT NULL CHECK (char_length(currency) = 3),
    source_kind TEXT NOT NULL,
    source_url TEXT,
    recorded_at BIGINT NOT NULL,
    effective_at BIGINT,
    is_current BOOLEAN NOT NULL,
    schedule_json TEXT
);

CREATE INDEX model_price_plans_model_idx
    ON model_price_plans(provider_id, upstream_model_id);
CREATE UNIQUE INDEX model_price_plans_current_idx
    ON model_price_plans(provider_id, upstream_model_id) WHERE is_current;

CREATE TABLE model_price_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price_plan_id BIGINT NOT NULL REFERENCES model_price_plans(id) ON DELETE CASCADE,
    item_code TEXT NOT NULL,
    unit_code TEXT NOT NULL,
    unit_size BIGINT NOT NULL CHECK (unit_size > 0),
    conditions_json TEXT NOT NULL,
    unit_price TEXT NOT NULL
);

CREATE INDEX model_price_rules_plan_idx ON model_price_rules(price_plan_id);
