CREATE TABLE model_routes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE CHECK (char_length(name) BETWEEN 1 AND 200),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 1 CHECK (version > 0),
    updated_at BIGINT NOT NULL
);

CREATE TABLE model_route_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT NOT NULL REFERENCES model_routes(id) ON DELETE CASCADE,
    model_id BIGINT NOT NULL REFERENCES model_mappings(id) ON DELETE RESTRICT,
    position BIGINT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (route_id, model_id),
    UNIQUE (route_id, position)
);

CREATE INDEX model_route_targets_model_id_idx ON model_route_targets(model_id);

INSERT INTO model_routes (name, updated_at)
SELECT alias, updated_at FROM model_mappings;

INSERT INTO model_route_targets (route_id, model_id, position)
SELECT route.id, model.id, 0
FROM model_mappings AS model
JOIN model_routes AS route ON route.name = model.alias;
