CREATE TABLE model_routes_v2 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK (char_length(name) BETWEEN 1 AND 200),
    protocol TEXT NOT NULL CHECK (protocol IN ('openai_chat', 'openai_responses', 'anthropic_messages')),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 1 CHECK (version > 0),
    updated_at BIGINT NOT NULL,
    UNIQUE (name, protocol)
);

CREATE TABLE model_route_targets_v2 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT NOT NULL REFERENCES model_routes_v2(id) ON DELETE CASCADE,
    model_id BIGINT NOT NULL REFERENCES model_mappings(id) ON DELETE RESTRICT,
    position BIGINT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (route_id, model_id),
    UNIQUE (route_id, position)
);

INSERT INTO model_routes_v2 (name, protocol, enabled, version, updated_at)
SELECT route.name, protocols.protocol, route.enabled, route.version, route.updated_at
FROM model_routes AS route
CROSS JOIN (VALUES ('openai_chat'), ('openai_responses'), ('anthropic_messages')) AS protocols(protocol)
WHERE EXISTS (
    SELECT 1 FROM model_route_targets AS target
    JOIN model_mappings AS model ON model.id = target.model_id
    WHERE target.route_id = route.id
      AND CASE protocols.protocol
          WHEN 'openai_chat' THEN model.openai_chat
          WHEN 'openai_responses' THEN model.openai_responses
          ELSE model.anthropic_messages
      END
);

INSERT INTO model_route_targets_v2 (route_id, model_id, position, enabled)
SELECT new_route.id, target.model_id, target.position, target.enabled
FROM model_routes_v2 AS new_route
JOIN model_routes AS old_route ON old_route.name = new_route.name
JOIN model_route_targets AS target ON target.route_id = old_route.id
JOIN model_mappings AS model ON model.id = target.model_id
WHERE CASE new_route.protocol
    WHEN 'openai_chat' THEN model.openai_chat
    WHEN 'openai_responses' THEN model.openai_responses
    ELSE model.anthropic_messages
END;

DROP TABLE model_route_targets;
DROP TABLE model_routes;
ALTER TABLE model_routes_v2 RENAME TO model_routes;
ALTER TABLE model_route_targets_v2 RENAME TO model_route_targets;
CREATE INDEX model_route_targets_model_id_idx ON model_route_targets(model_id);
