CREATE TABLE groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE CHECK (char_length(name) BETWEEN 1 AND 80),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL
);
INSERT INTO groups (id, name, enabled, updated_at) VALUES (1, 'default', TRUE, 0);
SELECT setval(pg_get_serial_sequence('groups', 'id'), 1);
ALTER TABLE providers ADD COLUMN group_id BIGINT NOT NULL DEFAULT 1 REFERENCES groups(id) ON DELETE RESTRICT;
ALTER TABLE providers DROP CONSTRAINT providers_name_key;
ALTER TABLE providers ADD UNIQUE(group_id, name);
ALTER TABLE model_mappings ADD COLUMN group_id BIGINT NOT NULL DEFAULT 1 REFERENCES groups(id) ON DELETE RESTRICT;
ALTER TABLE model_mappings DROP CONSTRAINT model_mappings_alias_key;
ALTER TABLE model_mappings ADD UNIQUE(group_id, alias);
ALTER TABLE model_routes ADD COLUMN group_id BIGINT NOT NULL DEFAULT 1 REFERENCES groups(id) ON DELETE RESTRICT;
ALTER TABLE model_routes DROP CONSTRAINT model_routes_v2_name_protocol_key;
ALTER TABLE model_routes ADD UNIQUE(group_id, name, protocol);
CREATE TABLE virtual_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES groups(id) ON DELETE RESTRICT,
    name TEXT NOT NULL,
    digest TEXT NOT NULL UNIQUE,
    prefix TEXT NOT NULL,
    all_routes BOOLEAN NOT NULL,
    route_ids TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    expires_at BIGINT,
    created_at BIGINT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX virtual_keys_group_idx ON virtual_keys(group_id);
