CREATE TABLE model_group_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES groups(id) ON DELETE RESTRICT,
    model_id BIGINT NOT NULL REFERENCES model_mappings(id) ON DELETE CASCADE,
    UNIQUE (group_id, model_id)
);
-- Catalog models remain unassigned until explicitly selected for a group.
ALTER TABLE model_mappings DROP CONSTRAINT model_mappings_group_id_alias_key;
ALTER TABLE model_mappings DROP COLUMN group_id;
CREATE INDEX model_group_memberships_model_id_idx ON model_group_memberships(model_id);
CREATE TABLE route_group_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES groups(id) ON DELETE RESTRICT,
    route_id BIGINT NOT NULL REFERENCES model_routes(id) ON DELETE CASCADE,
    UNIQUE (group_id, route_id)
);
-- Catalog routes remain unassigned until explicitly selected for a group.
ALTER TABLE model_routes DROP CONSTRAINT model_routes_group_id_name_protocol_key;
ALTER TABLE model_routes DROP COLUMN group_id;
CREATE INDEX route_group_memberships_route_id_idx ON route_group_memberships(route_id);
